
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIR LPAREN OR RPARENpattern : concatpattern : pattern OR concatconcat : termconcat : concat termterm : DIRterm :term : LPAREN pattern RPAREN'
    
_lr_action_items = {'DIR':([0,2,3,4,5,6,7,9,10,],[4,4,-3,-5,4,4,-4,4,-7,]),'LPAREN':([0,2,3,4,5,6,7,9,10,],[5,5,-3,-5,5,5,-4,5,-7,]),'OR':([0,1,2,3,4,5,6,7,8,9,10,],[-6,6,-1,-3,-5,-6,-6,-4,6,-2,-7,]),'$end':([0,1,2,3,4,6,7,9,10,],[-6,0,-1,-3,-5,-6,-4,-2,-7,]),'RPAREN':([2,3,4,5,6,7,8,9,10,],[-1,-3,-5,-6,-6,-4,10,-2,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pattern':([0,5,],[1,8,]),'concat':([0,5,6,],[2,2,9,]),'term':([0,2,5,6,9,],[3,7,3,3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pattern","S'",1,None,None,None),
  ('pattern -> concat','pattern',1,'p_pattern','fogelman.py',22),
  ('pattern -> pattern OR concat','pattern',3,'p_pattern_or','fogelman.py',27),
  ('concat -> term','concat',1,'p_concat','fogelman.py',32),
  ('concat -> concat term','concat',2,'p_concat_term','fogelman.py',37),
  ('term -> DIR','term',1,'p_term','fogelman.py',42),
  ('term -> <empty>','term',0,'p_term_empty','fogelman.py',47),
  ('term -> LPAREN pattern RPAREN','term',3,'p_term_paren','fogelman.py',52),
]
