from ground_scanner import Scanner


def test_bounds():
    file = open("test1.txt", "r")
    scanner = Scanner(file)
    assert scanner.dimensions() == ((495, 506), (1, 13))


def test_render():
    file = open("test1.txt", "r")
    expected = """
......+.......
............#.
.#..#.......#.
.#..#..#......
.#..#..#......
.#.....#......
.#.....#......
.#######......
..............
..............
....#.....#...
....#.....#...
....#.....#...
....#######...
"""
    scanner = Scanner(file)
    output = scanner.render()
    print(output)
    assert output == expected
